spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
  jpa:
    open-in-view: false
    show-sql: true
    datasource: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          exception-handling: ignore
  servlet:
    context-path: /filetransfer
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    static-path-pattern: "/static/**"
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
      
decorator:
  datasource:
    p6spy:
      enable-logging: true
      
file:
  dir: /data/fileTransfer/file/